manager/urls.py
from django.urls import path

from manager.views import (
    index,
    learn_more,
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    PositionListView,
    PositionDetailView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    TaskTypeListView,
    TaskTypeDetailView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/create", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path("positions/<int:pk>/", PositionDetailView.as_view(), name="position-detail"),
    path("positions/create/", PositionCreateView.as_view(), name="position-create"),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path("task-types/", TaskTypeListView.as_view(), name="task-type-list"),
    path("task-types/<int:pk>/", TaskTypeDetailView.as_view(), name="task-type-detail"),
    path("task-types/create/", TaskTypeCreateView.as_view(), name="task-type-create"),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path("learn-more/", learn_more, name="learn-more"),
]

app_name = "manager"

task_manager/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from task_manager import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("manager.urls", namespace="manager")),
    path("__debug__/", include("debug_toolbar.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from task_manager import settings


class TaskType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Position(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(
        Position, on_delete=models.CASCADE, null=True, related_name="workers"
    )
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField()
    password = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"


class Task(models.Model):
    PRIORITY_CHOICES = (
        ("low", "Low"),
        ("medium", "Medium"),
        ("high", "High"),
    )

    name = models.CharField(max_length=63)
    description = models.TextField()
    deadline = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES)
    task_type = models.ForeignKey(
        TaskType, on_delete=models.CASCADE, related_name="tasks"
    )
    assignees = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="tasks")

    def __str__(self):
        return self.name

manager/forms.py
from django import forms


class WorkerSearchForm(forms.Form):
    query = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Username/first name/last name"}),
    )


class PositionsSearchForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Position name"}),
    )


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Task name"}),
    )


class TaskOrderForm(forms.Form):
    sort_by = forms.MultipleChoiceField(
        choices=[("deadline", "Deadline"), ("priority", "Priority")],
        required=False,
        label="Sort by",
        widget=forms.CheckboxSelectMultiple(),
    )
    active_only = forms.BooleanField(
        required=False,
        label="Active tasks only",
        widget=forms.CheckboxInput(),
    )


class TaskTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Task type name"}),
    )

manager/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.db.models.query import QuerySet

from typing import Any, Dict

from manager.forms import (
    WorkerSearchForm,
    PositionsSearchForm,
    TaskTypeSearchForm,
    TaskSearchForm,
    TaskOrderForm,
)
from manager.models import Task, Worker, Position, TaskType


def index(request) -> HttpResponse:
    return render(request, "manager/index.html")


def learn_more(request)  -> HttpResponse:
    return render(request, "includes/learn_more.html")


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 7

    def get_context_data(self, *, object_list=None, **kwargs) -> Dict[str, Any]:
        context = super(TaskListView, self).get_context_data(**kwargs)
        search_form = TaskSearchForm(self.request.GET)
        order_form = TaskOrderForm(self.request.GET)

        context["search_form"] = search_form
        context["order_form"] = order_form

        return context

    def get_queryset(self) -> "QuerySet[Task]":
        queryset = super(TaskListView, self).get_queryset()
        name = self.request.GET.get("name")
        if name:
            queryset = queryset.filter(name__icontains=name)

        sort_by = self.request.GET.getlist("sort_by")

        if "deadline" in sort_by:
            queryset = queryset.order_by("deadline")
        elif "priority" in sort_by:
            queryset = queryset.order_by("priority")

        active_only = self.request.GET.get("active_only", False)
        if active_only:
            queryset = queryset.filter(is_completed=False)

        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("manager:task-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("manager:task-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("manager:task-list")


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    context_object_name = "worker_list"
    paginate_by = 7

    def get_queryset(self) -> "QuerySet[Worker]":
        queryset = super(WorkerListView, self).get_queryset()
        query = self.request.GET.get("query")

        if query:
            queryset = queryset.filter(
                Q(username__icontains=query)
                | Q(first_name__icontains=query)
                | Q(last_name__icontains=query)
            )

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs) -> Dict[str, Any]:
        context = super(WorkerListView, self).get_context_data(**kwargs)
        context["search_form"] = WorkerSearchForm(
            initial={
                "query": self.request.GET.get("query", ""),
            }
        )
        return context


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    fields = "__all__"
    success_url = reverse_lazy("manager:worker-list")


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    fields = "__all__"
    success_url = reverse_lazy("manager:worker-list")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("manager:worker-list")


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    template_name = "manager/position_list.html"
    paginate_by = 7

    def get_context_data(self, *, object_list=None, **kwargs) -> Dict[str, Any]:
        context = super(PositionListView, self).get_context_data(**kwargs)
        context["search_form"] = PositionsSearchForm(
            initial={
                "name": self.request.GET.get("name", ""),
            }
        )
        return context

    def get_queryset(self) -> "QuerySet[Position]":
        queryset = super(PositionListView, self).get_queryset()
        name = self.request.GET.get("name")
        if name:
            queryset = queryset.filter(name__icontains=name)
        return queryset


class PositionDetailView(LoginRequiredMixin, generic.DetailView):
    model = Position


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("manager:position-list")


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("manager:position-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("manager:position-list")


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    template_name = "manager/task_type_list.html"
    paginate_by = 7

    def get_context_data(self, *, object_list=None, **kwargs) -> Dict[str, Any]:
        context = super(TaskTypeListView, self).get_context_data(**kwargs)
        context["search_form"] = TaskTypeSearchForm(
            initial={
                "name": self.request.GET.get("name", ""),
            }
        )
        return context

    def get_queryset(self) -> "QuerySet[TaskType]":
        queryset = super(TaskTypeListView, self).get_queryset()
        name = self.request.GET.get("name")
        if name:
            queryset = queryset.filter(name__icontains=name)
        return queryset


class TaskTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = TaskType
    template_name = "manager/task_type_detail.html"


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("manager:task-type-list")


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("manager:task-type-list")


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    success_url = reverse_lazy("manager:task-type-list")

templates/manager/index.html
{% extends "base.html" %}

{% block header %}
  {% include "includes/header.html" %}
{% endblock %}

templates/manager/position_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div style="text-align: center; margin-top: 35px">
    <h1>Are you sure you want to delete this position?</h1>
    <form action="" method="post">
      {% csrf_token %}
      <hr>
      <h3 id="user-delete-marker">{{ position.name }}</h3>
      <hr>
      <p class="warning-text">
        This information won't be available to restore.
        All boundaries with position will be lost!
      </p>
      <div style="margin-top: 50px">
        <input type="submit" value="Yes" class="btn btn-danger del-button">
        <input type="submit" value="Cancel" class="btn btn-primary del-button">
      </div>
    </form>
</div>
{% endblock %}

templates/manager/position_detail.html
{% extends "base.html" %}

{% block content %}
  <div style="text-align: center; margin-top: 50px">
    <h2>Position detail</h2>
      <p>
        <strong>Position:</strong>
        {{ position.name }}
      </p>
      {% if position.worker_set.all %}
        <p>
          <strong>All employees who have this position:</strong>
        </p>
        <ul>
          {% for worker in position.worker_set.all %}
            <li>
              <a href="{% url 'manager:worker-detail' worker.id %}">{{ worker.first_name }} {{ worker.last_name }}</a>
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p>
          <strong>There are no employees with this position for now.</strong>
        </p>
      {% endif %}
    </div>
    <div style="margin-right: 35%; margin-top: 50px">
    <input type="button" class="btn btn-secondary task-detail-but" value="Delete" onclick="window.location.href='{% url 'manager:position-delete' position.id %}'">
      </div>
    <div>
      <input type="button" class="btn btn-secondary task-detail-but" value="Update" onclick="window.location.href='{% url 'manager:position-update' position.id %}'">
    </div>
{% endblock %}

templates/manager/position_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container mt-4" style="margin-left: 275px">
    <h1>{{ object|yesno:"Update,Create" }} Position</h1>
    <form action="" method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-6">
          {{ form|crispy }}
          <div class="mt-4">
            <input type="submit" value="Submit" class="btn btn-secondary create-task-but">
          </div>
        </div>
      </div>
    </form>
  </div>
  <div style="height: 200px;">
  </div>
{% endblock %}

templates/manager/position_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Positions</h1>
  <form method="get" action="">
    <div class="row search-task-types">
      <div class="col-2 search-task-types-field">
        {{ search_form | crispy }}
      </div>
      <div class="col-1">
        <input type="submit" value="🔎" class="btn btn-secondary">
      </div>
    </div>
  </form>
  <hr>
  {% if position_list %}
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for position in position_list %}
          <tr>
            <td>{{ position.id }}</td>
            <td><a href="{% url 'manager:position-detail' pk=position.id %}">{{ position.name }}</a></td>
            <td>
              <a href="{% url 'manager:position-update' position.id %}">Update</a>
            </td>
            <td>
              <a href="{% url 'manager:position-delete' position.id %}">Delete</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There are no positions at this time.</p>
  {% endif %}
  <input type="button" class="btn btn-secondary create-task-but" value="Create" onclick="window.location.href='{% url 'manager:position-create' %}'">
{% endblock %}

templates/manager/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div style="text-align: center; margin-top: 35px">
  <h1>Are you sure you want to delete this task?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <hr>
    <h3 id="user-delete-marker">{{ task.name }}</h3>
    <p>{{ task.description }}</p>
    <hr>
    <p class="warning-text">
      This information won't be available to restore.
      All boundaries with position will be lost!
    </p>
    <div style="margin-top: 50px">
      <input type="submit" value="Yes" class="btn btn-danger del-button">
      <input type="submit" value="Cancel" class="btn btn-primary del-button">
    </div>
  </form>
</div>
{% endblock %}

templates/manager/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container mt-4" style="margin-left: 275px">
    <h1>{{ object|yesno:"Update,Create" }} Task</h1>
    <form action="" method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-6">
          {{ form|crispy }}
          <div class="mt-4">
            <input type="submit" value="Submit" class="btn btn-secondary create-task-but">
          </div>
        </div>
      </div>
    </form>
  </div>
  <div style="height: 200px;"></div>
{% endblock %}

templates/manager/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Tasks</h1>

  <form method="get" action="">
    <div class="row search-task-types">
      <div class="col-2 search-task-types-field">
        {{ search_form | crispy }}
      </div>
      <div class="col-1">
        <input type="submit" value="🔎" class="btn btn-secondary">
      </div>
    </div>
  </form>

  <hr>
  {% if task_list %}
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for task in task_list %}
          <tr>
            <td>{{ task.id }}</td>
            <td><a href="{% url 'manager:task-detail' pk=task.id %}">{{ task.name }}</a></td>
            <td><a href="{% url 'manager:task-update' task.id %}">Edit</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There are no tasks at this time.</p>
  {% endif %}

  <input type="button" class="btn btn-secondary create-tasks-but" value="Create" onclick="window.location.href='{% url 'manager:task-create' %}'">

  <form class="form-inline">
    <input type="submit" class="btn btn-secondary mb-2" value="Apply">
      <div class="form-group group-sort mb-2">
          <label class="sr-only" for="inlineFormInputGroupUsername2">Sort by</label>
          {{ order_form.sort_by }}
                {{ order_form.active_only }}
          <label class="form-check-label" for="inlineFormCheck">
              Active tasks only
          </label>
      </div>
  </form>

{% endblock %}

templates/manager/tasktype_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div style="text-align: center; margin-top: 35px">
    <h1>Are you sure you want to delete this task type?</h1>
    <form action="" method="post">
      {% csrf_token %}
      <hr>
      <h3 id="user-delete-marker">
        {{ tasktype.name }}
      </h3>
      {% if tasktype.task_set.all %}
        <p>Related tasks:</p>
        <ul>
          {% for task in tasktype.task_set.all %}
            <li>{{ task.name }}</li>
          {% endfor %}
        </ul>
      {% endif %}
      <hr>
      <p class="warning-text">
        This information won't be available to restore.
        All boundaries with position will be lost!
      </p>
    <div style="margin-top: 50px">
      <input type="submit" value="Yes" class="btn btn-danger del-button">
      <input type="submit" value="Cancel" class="btn btn-primary del-button">
    </div>
  </form>
</div>
{% endblock %}

templates/manager/tasktype_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container mt-4" style="margin-left: 275px">
    <h1>{{ object|yesno:"Update,Create" }} Task Type</h1>
    <form action="" method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-6">
          {{ form|crispy }}
          <div class="mt-4">
            <input type="submit" value="Submit" class="btn btn-secondary create-task-but">
          </div>
        </div>
      </div>
    </form>
  </div>
  <div style="height: 200px;"></div>
{% endblock %}

templates/manager/worker_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div style="text-align: center; margin-top: 35px">
    <h1>Are you sure you want to delete this employee?</h1>
    <form action="" method="post">
      {% csrf_token %}
      <hr>
      <h3 id="user-delete-marker">
        {{ worker.first_name }} {{ worker.last_name }} ({{ worker.username }})
      </h3>
      <p>Position: {{ worker.position }}</p>
      <hr>
      <p class="warning-text">
        This information won't be available to restore.
        All boundaries with position will be lost!
      </p>
    <div style="margin-top: 50px">
      <input type="submit" value="Yes" class="btn btn-danger del-button">
      <input type="submit" value="Cancel" class="btn btn-primary del-button">
    </div>
  </form>
</div>
{% endblock %}


templates/manager/worker_detail.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h2>{{ worker.first_name }} {{ worker.last_name }}</h2>
  <hr>
  <table class="table table-bordered">
    <tbody>
      <tr>
        <th>Username</th>
        <td>{{ worker.username }}</td>
      </tr>
      <tr>
        <th>Email</th>
        <td>{{ worker.email }}</td>
      </tr>
      <tr>
        <th>Position</th>
        <td>{{ worker.position }}</td>
      </tr>
      <tr>
        <th>Current task</th>
        <td>
          {% if worker.tasks.all %}
            {% for task in worker.tasks.all %}
              <a href="{% url 'manager:task-detail' task.id %}">{{ task.name }}</a>
            {% endfor %}
          {% else %}
            <p>No active tasks.</p>
          {% endif %}
        </td>
      </tr>
    </tbody>
  </table>
  <hr>
  <input type="button" class="btn btn-secondary task-detail-but" value="Delete" onclick="window.location.href='{% url 'manager:worker-delete' worker.id %}'">
  <input type="button" class="btn btn-secondary task-detail-but" value="Update" onclick="window.location.href='{% url 'manager:worker-update' worker.id %}'">

{% endblock %}

templates/manager/worker_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container mt-4" style="margin-left: 275px">
    <h1>{{ object|yesno:"Update,Create" }} Worker</h1>
    <form action="" method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-6">
          {{ form|crispy }}
          <div class="mt-4">
            <input type="submit" value="Submit" class="btn btn-secondary create-task-but">
          </div>
        </div>
      </div>
    </form>
  </div>
  <div style="height: 200px;"></div>
{% endblock %}

templates/manager/worker_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Employees</h1>
  <form method="get" action="">
    <div class="row search-task-types">
      <div class="col-2 search-task-types-field">
        {{ search_form | crispy }}
      </div>
      <div class="col-1">
        <input type="submit" value="🔎" class="btn btn-secondary">
      </div>
    </div>
  </form>
  <hr>
  {% if worker_list %}
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Username</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for worker in worker_list %}
          <tr>
            <td>{{ worker.id }}</td>
            <td><a href="{% url 'manager:worker-detail' pk=worker.id %}">{{ worker.first_name }} {{ worker.last_name }}</a></td>
            <td>{{ worker.username }}</td>
            <td>
              <a href="{% url 'manager:worker-update' worker.id %}">Update</a>
            </td>
            <td>
              <a href="{% url 'manager:worker-delete' worker.id %}">Delete</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There are no workers at this time.</p>
  {% endif %}
  <input type="button" class="btn btn-secondary create-task-but" value="Create" onclick="window.location.href='{% url 'manager:worker-create' %}'">
{% endblock %}