manager/urls.py
from django.urls import path

from manager.views import (
    index,
    learn_more,
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    WorkerListView,
    WorkerDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    PositionListView,
    PositionDetailView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    TaskTypeListView,
    TaskTypeDetailView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
)

urlpatterns = [
    path("", index, name="index"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/create", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path("positions/<int:pk>/", PositionDetailView.as_view(), name="position-detail"),
    path("positions/create/", PositionCreateView.as_view(), name="position-create"),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path("task-types/", TaskTypeListView.as_view(), name="task-type-list"),
    path("task-types/<int:pk>/", TaskTypeDetailView.as_view(), name="task-type-detail"),
    path("task-types/create/", TaskTypeCreateView.as_view(), name="task-type-create"),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path("learn-more/", learn_more, name="learn-more"),
]

app_name = "manager"

task_manager/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from task_manager import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("manager.urls", namespace="manager")),
    path("__debug__/", include("debug_toolbar.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer.html
<footer class="foot-bottom bg-dark py-4 mt-auto">
    <button class="btn-info"><a id="back-link" href="javascript:history.back()">Back</a></button>
    <div class="container px-5">
        <div class="row align-items-center justify-content-between flex-column flex-sm-row">
            <div class="col-auto"><div class=" ml-3 small m-0 text-white">Pet Project &copy; 2023</div></div>
            <div class="col-auto">
                <a class="link-light small" href="https://github.com/anna-lybid/task-manager" target="_blank">Git Hub</a>
                <span class="text-white mx-1">&middot;</span>
                <a class="link-light small" href="#!">Contact</a>
            </div>
        </div>
    </div>
</footer>

templates/includes/header.html
<header class="top-header bg-dark py-5">
    <div class="container px-5">
        <div class="row gx-5 align-items-center justify-content-center">
            <div class="col-lg-8 col-xl-7 col-xxl-6">
                <div class="my-5 text-center text-xl-start">
                    <h1 class="display-5 fw-bolder text-white mb-2">Distribute tasks efficiently, with clarity and ease.</h1>
                    {% if not user.is_authenticated %}
                      <p class="lead fw-normal text-white-50 mb-4">Please log in to continue</p>
                    {% endif %}
                    <div class="d-grid gap-3 d-sm-flex justify-content-sm-center justify-content-xl-start">
                      {% if not user.is_authenticated %}
                        <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'login'%}?next={{request.path}}">Get Started</a>
                      {% endif %}
                        <a class="btn btn-outline-light btn-lg px-4" href="{% url 'manager:learn-more' %}">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-xl-5 col-xxl-6 d-none d-xl-block text-center"><img class="img-fluid rounded-3 my-5" src="static/images/pexels-breakingpic-3299.jpg" alt="..." /></div>
        </div>
    </div>
</header>

templates/includes/learn_more.html
{% extends "base.html" %}

{% block content %}
    <section class="py-5">
        <div class="container px-5 my-5">
            <div class="row gx-5 justify-content-center">
                <div class="col-lg-6">
                    <div class="text-center mb-5">
                        <h1 class="fw-bolder">What you can do:</h1>
                        <hr>
                        <ul>
                          <li>add, delete or update positions, employees, tasks, task types</li>
                          <li>get general lists</li>
                          <li>get detailed information about each task or employee</li>
                          <li>sort tasks by status</li>
                          <li>order tasks by deadline</li>
                          <li>receive a list by prioritizing</li>
                          <li>assign executors</li>
                        </ul>
                      </div>
                </div>
            </div>
            <div class="row gx-5">
            </div>
            <div class="row gx-5 justify-content-center">
                <div class="col-lg-6">
                    <div class="text-center mb-5">
                        <a class="text-decoration-none" href="{% url 'manager:index' %}">
                            To home page
                            <i class="bi-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/includes/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <ul class="user-ul">
    {% if user.is_authenticated %}
      <li class="list-group-item list-group-item-action active" aria-current="true"><a class="user-display" href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
      <li class="list-group-item list-group-item-action active" aria-current="true"><a class="user-display" href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
    {% else %}
      <li class="list-group-item list-group-item-action active" aria-current="true"><a class="user-display" href="{% url 'login'%}?next={{request.path}}">Login</a></li>
    {% endif %}
  </ul>
    <div class="container px-5">
      <a class="navbar-brand nav-content" href="{% url 'manager:index' %}">Task manager</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item"><a class="nav-link" href="{% url 'manager:index' %}">Home</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'manager:task-list' %}">Tasks</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'manager:worker-list' %}">Employees</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'manager:position-list' %}">Positions</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'manager:task-type-list' %}">Task types</a></li>
        </ul>
      </div>
    </div>
</nav>

templates/includes/pagination.html
<div id="fixed-pagination">
  {% if is_paginated %}
    <div class="pagination-container">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
          </li>
        {% endif %}
        <li class="page-item active">
          <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
        </li>
        {% if page_obj.has_next %}
          <li class="page-item">
            <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
          </li>
        {% endif %}
      </ul>
    </div>
  {% endif %}
</div>